data:extend{
	{
		type="string-setting",
		name="btqbuslodtswfowap-filter-item",
		setting_type="runtime-per-user",
		default_value="no-item",
	},
	{
		type="string-setting",
		name="btqbuslodtswfowap-auto-filter",
		setting_type="runtime-per-user",
		default_value="no-auto",
		allowed_values={
			"no-auto",
			"single-output",
			"fully-defined",
		},
	},
}
